<?php
$sooperdefaults = array(
  'slideshowkit_enable'               => 1,
  'cycle_invoke'                      => 'div.slideshow div > ul',
  'cycle_fx'                          => 'scrollHorz',
  'cycle_timeout'                     => 4000,
  'cycle_continuous'                  => 0,
  'cycle_speed'                       => 800,
  'cycle_pagerEvent'                  => 'mouseover',
  'cycle_easing'                      => 'linear',
  'cycle_random'                      => 0,
  'cycle_pause'                       => 0,
  'cycle_pauseOnPagerHover'           => 1,
  'cycle_delay'                       => 0,
);