<?php
$sooperdefaults = array(
  'sooperfish_invoke'                  => '#navbar > ul',
  'sooperfish_width'                   => 200,
  'sooperfish_enable'                  => 1,
  'sooperfish_delay'                   => 500,
  'sooperfish_dualcolumn'              => 5,
  'sooperfish_triplecolumn'            => 12,
  'sooperfish_speed_show'              => 500,
  'sooperfish_speed_hide'              => 500,
  'sooperfish_easing_show'             => 'swing',
  'sooperfish_easing_hide'             => 'swing',
  'sooperfish_properties_show'         => array('height' => TRUE),
  'sooperfish_properties_hide'         => array('opacity' => TRUE, 'height' => TRUE),
);